title: LABEXAM
author: msvahedi
description: >
  This is ALL about our LABEXAM
baseurl: "/blog"
url: "https://labexam.github.io/"

social:
  name: MSVahedi
  links:
    - https://twitter.com/hello
    - https://www.facebook.com/hello
    - https://www.linkedin.com/in/hello
    - https://plus.google.com/hello
    - https://github.com/hello
    - https://keybase.io/hello

navigation:
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: .\assets\images\jungleee.png
email: hello@gmail.com
github_username:  msvahedi

# disqus:
#   shortname: disqus_shortname
service_worker: true

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag